### PR TITLE
Use a discover script to probe pkg-config for link flags

### PR DESCRIPTION
**Pull request by mbacarella**
This fixes installing on MacOS with homebrew.

### CODE REVIEW

**Comment by sanette** [comment]
I cannot test it since I don't have a mac, but it sounds good to me and it still works on my linux machine.

**Comment by sanette** [comment]
I suppose we need to apply this to 
https://github.com/sanette/tsdl-mixer
and
https://github.com/sanette/tsdl-image
as well?

**Comment by sanette** [comment]
what is the result of `conf.libs` on your system?

**Comment by mbacarella** [comment]
> what is the result of `conf.libs` on your system?

Assuming you mean what gets written to `c_library_flags.sexp`? It's:
```sexp
("-L/opt/homebrew/lib" "-lSDL2_ttf" "-lSDL2")
```

**Comment by sanette** [comment]
ok, thanks. Let's merge ;)

**Pull request merged**
